service: helloworld-app

provider:
    name: aws
    runtime: nodejs14.x
    memorySize: 2048
    stage: dev
    timeout: 15

  functions:
    app:
      handler: app.server # reference the file and exported method
      events: # events trigger lambda functions
        - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
        - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
